//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMATION_INDIVIDUAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FORMATION_INDIVIDUAL()
        {
            this.ADHERENT = new HashSet<ADHERENT>();
        }
    
        public int ID_FORMATIONINDIVIDUAL { get; set; }
        public string NOM_FR { get; set; }
        public string SECTEUR_ACTIVITE { get; set; }
        public string MODE_REGLEMENT { get; set; }
        public string Etat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADHERENT> ADHERENT { get; set; }
    }
}
