//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMATION_GROUPE
    {
        public int ID_FORMATIONGROUPE { get; set; }
        public string NOM_FR { get; set; }
        public string Nom_Entrprise { get; set; }
        public string SECTEUR_ACTIVITE { get; set; }
        public string MISSION { get; set; }
        public string OBJECTIF { get; set; }
        public Nullable<int> EFFECTIF { get; set; }
        public string BESOIN_INDIVIDUELE { get; set; }
        public string BESOIN { get; set; }
    }
}
