//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace site.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjetFinFormationEntities1 : DbContext
    {
        public ProjetFinFormationEntities1()
            : base("name=ProjetFinFormationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADHERENT> ADHERENT { get; set; }
        public virtual DbSet<CLIENT_EVENEMENT> CLIENT_EVENEMENT { get; set; }
        public virtual DbSet<CLIENT_SALLE> CLIENT_SALLE { get; set; }
        public virtual DbSet<FORMATION_GROUPE> FORMATION_GROUPE { get; set; }
        public virtual DbSet<FORMATION_INDIVIDUAL> FORMATION_INDIVIDUAL { get; set; }
        public virtual DbSet<SALLE> SALLE { get; set; }
    }
}
